{
  "stats": {
    "submitted": 180,
    "finished": 179,
    "running": 1
  },
  "data": [
    {
      "config_id": 1,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 38.379114,
      "status": 2,
      "starttime": 1744128973.570001,
      "endtime": 1744128973.5754979,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 2,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 38.391817,
      "status": 2,
      "starttime": 1744128973.58228,
      "endtime": 1744128973.588259,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 3,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 38.40216,
      "status": 2,
      "starttime": 1744128973.592593,
      "endtime": 1744128973.5978281,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 4,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 38.412396,
      "status": 2,
      "starttime": 1744128973.602626,
      "endtime": 1744128973.607979,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 5,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 38.422491,
      "status": 2,
      "starttime": 1744128973.612473,
      "endtime": 1744128973.617837,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 6,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 38.43367,
      "status": 2,
      "starttime": 1744128973.6232388,
      "endtime": 1744128973.628788,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 7,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 38.444088,
      "status": 2,
      "starttime": 1744128973.6333241,
      "endtime": 1744128973.638902,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 8,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 38.454505,
      "status": 2,
      "starttime": 1744128973.643397,
      "endtime": 1744128973.648952,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 9,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 38.46501,
      "status": 2,
      "starttime": 1744128973.653693,
      "endtime": 1744128973.6591082,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 10,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 38.475019,
      "status": 2,
      "starttime": 1744128973.663316,
      "endtime": 1744128973.6684108,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 11,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 38.804208,
      "status": 2,
      "starttime": 1744128973.993259,
      "endtime": 1744128973.9989161,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 12,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 38.814909,
      "status": 2,
      "starttime": 1744128974.003843,
      "endtime": 1744128974.00892,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 13,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 38.825463,
      "status": 2,
      "starttime": 1744128974.014179,
      "endtime": 1744128974.019645,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 14,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 38.836974,
      "status": 2,
      "starttime": 1744128974.025308,
      "endtime": 1744128974.030422,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 15,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 38.847877,
      "status": 2,
      "starttime": 1744128974.036005,
      "endtime": 1744128974.0419421,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 16,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 38.859214,
      "status": 2,
      "starttime": 1744128974.0474188,
      "endtime": 1744128974.0528462,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 17,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 38.871224,
      "status": 2,
      "starttime": 1744128974.059293,
      "endtime": 1744128974.064707,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 18,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 38.882679,
      "status": 2,
      "starttime": 1744128974.0704699,
      "endtime": 1744128974.0764549,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 19,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 39.379331,
      "status": 2,
      "starttime": 1744128974.611525,
      "endtime": 1744128974.616522,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 20,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 39.38976,
      "status": 2,
      "starttime": 1744128974.621736,
      "endtime": 1744128974.626851,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 21,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 39.400477,
      "status": 2,
      "starttime": 1744128974.6322591,
      "endtime": 1744128974.637717,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 22,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 39.411488,
      "status": 2,
      "starttime": 1744128974.643091,
      "endtime": 1744128974.6483579,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 23,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 39.422664,
      "status": 2,
      "starttime": 1744128974.6539671,
      "endtime": 1744128974.6592782,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 24,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 39.433658,
      "status": 2,
      "starttime": 1744128974.664729,
      "endtime": 1744128974.669919,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 25,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 39.445774,
      "status": 2,
      "starttime": 1744128974.6765702,
      "endtime": 1744128974.68176,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 26,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 39.458646,
      "status": 2,
      "starttime": 1744128974.689025,
      "endtime": 1744128974.694828,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 27,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 39.479191,
      "status": 2,
      "starttime": 1744128974.708768,
      "endtime": 1744128974.714336,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 28,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 39.940072,
      "status": 2,
      "starttime": 1744128975.170279,
      "endtime": 1744128975.175691,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 29,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 39.951393,
      "status": 2,
      "starttime": 1744128975.1813781,
      "endtime": 1744128975.186723,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 30,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 39.963697,
      "status": 2,
      "starttime": 1744128975.193344,
      "endtime": 1744128975.198524,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 31,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 39.976233,
      "status": 2,
      "starttime": 1744128975.205328,
      "endtime": 1744128975.210783,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 32,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 39.987893,
      "status": 2,
      "starttime": 1744128975.216792,
      "endtime": 1744128975.222216,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 33,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 40.001194,
      "status": 2,
      "starttime": 1744128975.2294881,
      "endtime": 1744128975.2350478,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 34,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 40.014069,
      "status": 2,
      "starttime": 1744128975.241984,
      "endtime": 1744128975.247126,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 35,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 40.035118,
      "status": 2,
      "starttime": 1744128975.262898,
      "endtime": 1744128975.2681248,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 36,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 40.615459,
      "status": 2,
      "starttime": 1744128975.843246,
      "endtime": 1744128975.848518,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 37,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 40.627912,
      "status": 2,
      "starttime": 1744128975.855636,
      "endtime": 1744128975.86076,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 38,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 40.640595,
      "status": 2,
      "starttime": 1744128975.868314,
      "endtime": 1744128975.873625,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 39,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 40.65221,
      "status": 2,
      "starttime": 1744128975.8797948,
      "endtime": 1744128975.884921,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 40,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 40.664739,
      "status": 2,
      "starttime": 1744128975.892122,
      "endtime": 1744128975.897483,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 41,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 40.677162,
      "status": 2,
      "starttime": 1744128975.9042392,
      "endtime": 1744128975.909655,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 42,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 40.68958,
      "status": 2,
      "starttime": 1744128975.916555,
      "endtime": 1744128975.921912,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 43,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 41.25637,
      "status": 2,
      "starttime": 1744128976.5296881,
      "endtime": 1744128976.5339189,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 44,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 41.268327,
      "status": 2,
      "starttime": 1744128976.541217,
      "endtime": 1744128976.5455139,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 45,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 41.282745,
      "status": 2,
      "starttime": 1744128976.55558,
      "endtime": 1744128976.5608141,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 46,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 41.295077,
      "status": 2,
      "starttime": 1744128976.5675468,
      "endtime": 1744128976.572941,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 47,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 41.308108,
      "status": 2,
      "starttime": 1744128976.580266,
      "endtime": 1744128976.5854871,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 48,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 41.322811,
      "status": 2,
      "starttime": 1744128976.595005,
      "endtime": 1744128976.600513,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 49,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 41.33606,
      "status": 2,
      "starttime": 1744128976.6083379,
      "endtime": 1744128976.613754,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 50,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 41.348708,
      "status": 2,
      "starttime": 1744128976.620901,
      "endtime": 1744128976.6265469,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 51,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 41.968584,
      "status": 2,
      "starttime": 1744128977.2435699,
      "endtime": 1744128977.2483141,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 52,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 41.981003,
      "status": 2,
      "starttime": 1744128977.255745,
      "endtime": 1744128977.26096,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 53,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 41.994494,
      "status": 2,
      "starttime": 1744128977.268734,
      "endtime": 1744128977.273985,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 54,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 42.008233,
      "status": 2,
      "starttime": 1744128977.282024,
      "endtime": 1744128977.287643,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 55,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 42.02256,
      "status": 2,
      "starttime": 1744128977.296191,
      "endtime": 1744128977.3014662,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 56,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 42.036226,
      "status": 2,
      "starttime": 1744128977.3095748,
      "endtime": 1744128977.314945,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 57,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 42.049545,
      "status": 2,
      "starttime": 1744128977.322706,
      "endtime": 1744128977.3282812,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 58,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 42.063313,
      "status": 2,
      "starttime": 1744128977.336205,
      "endtime": 1744128977.342154,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 59,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 42.809617,
      "status": 2,
      "starttime": 1744128978.083495,
      "endtime": 1744128978.0889962,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 60,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 42.823936,
      "status": 2,
      "starttime": 1744128978.097543,
      "endtime": 1744128978.103004,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 61,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 42.838028,
      "status": 2,
      "starttime": 1744128978.111485,
      "endtime": 1744128978.116628,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 62,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 42.851992,
      "status": 2,
      "starttime": 1744128978.125212,
      "endtime": 1744128978.130543,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 63,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 42.86616,
      "status": 2,
      "starttime": 1744128978.1393301,
      "endtime": 1744128978.144636,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 64,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 42.879983,
      "status": 2,
      "starttime": 1744128978.1529338,
      "endtime": 1744128978.158989,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 65,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 42.894212,
      "status": 2,
      "starttime": 1744128978.16732,
      "endtime": 1744128978.1729448,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 66,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 42.908686,
      "status": 2,
      "starttime": 1744128978.1815538,
      "endtime": 1744128978.1868951,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 67,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 43.732059,
      "status": 2,
      "starttime": 1744128979.007652,
      "endtime": 1744128979.0128078,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 68,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 43.746122,
      "status": 2,
      "starttime": 1744128979.021481,
      "endtime": 1744128979.026827,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 69,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 43.760863,
      "status": 2,
      "starttime": 1744128979.035839,
      "endtime": 1744128979.041183,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 70,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 43.778261,
      "status": 2,
      "starttime": 1744128979.086517,
      "endtime": 1744128979.099214,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 71,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 43.796395,
      "status": 2,
      "starttime": 1744128979.110302,
      "endtime": 1744128979.116593,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 72,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 43.814289,
      "status": 2,
      "starttime": 1744128979.127521,
      "endtime": 1744128979.133676,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 73,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 43.832596,
      "status": 2,
      "starttime": 1744128979.145587,
      "endtime": 1744128979.151186,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 74,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 43.847929,
      "status": 2,
      "starttime": 1744128979.1608472,
      "endtime": 1744128979.166219,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 75,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 43.882413,
      "status": 2,
      "starttime": 1744128979.1953468,
      "endtime": 1744128979.200501,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 76,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 44.664355,
      "status": 2,
      "starttime": 1744128979.979038,
      "endtime": 1744128979.984254,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 77,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 44.679192,
      "status": 2,
      "starttime": 1744128979.993678,
      "endtime": 1744128979.999377,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 78,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 44.694167,
      "status": 2,
      "starttime": 1744128980.008624,
      "endtime": 1744128980.013758,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 79,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 44.708926,
      "status": 2,
      "starttime": 1744128980.023377,
      "endtime": 1744128980.02876,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 80,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 44.723822,
      "status": 2,
      "starttime": 1744128980.0380852,
      "endtime": 1744128980.043603,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 81,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 44.738789,
      "status": 2,
      "starttime": 1744128980.052885,
      "endtime": 1744128980.058431,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 82,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 44.755887,
      "status": 2,
      "starttime": 1744128980.0729768,
      "endtime": 1744128980.0782971,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 83,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 45.619624,
      "status": 2,
      "starttime": 1744128980.9403389,
      "endtime": 1744128980.9457438,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 84,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 45.634694,
      "status": 2,
      "starttime": 1744128980.95518,
      "endtime": 1744128980.960876,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 85,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 45.650555,
      "status": 2,
      "starttime": 1744128980.9709709,
      "endtime": 1744128980.976686,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 86,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 45.665626,
      "status": 2,
      "starttime": 1744128980.985986,
      "endtime": 1744128980.991977,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 87,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 45.681626,
      "status": 2,
      "starttime": 1744128981.001995,
      "endtime": 1744128981.007884,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 88,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 45.698229,
      "status": 2,
      "starttime": 1744128981.01841,
      "endtime": 1744128981.024519,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 89,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 45.715074,
      "status": 2,
      "starttime": 1744128981.035139,
      "endtime": 1744128981.041122,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 90,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 45.731139,
      "status": 2,
      "starttime": 1744128981.051179,
      "endtime": 1744128981.056701,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 91,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 46.771319,
      "status": 2,
      "starttime": 1744128982.09798,
      "endtime": 1744128982.103116,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 92,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 46.786289,
      "status": 2,
      "starttime": 1744128982.112677,
      "endtime": 1744128982.117903,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 93,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 46.802359,
      "status": 2,
      "starttime": 1744128982.128507,
      "endtime": 1744128982.133642,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 94,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 46.817936,
      "status": 2,
      "starttime": 1744128982.1439638,
      "endtime": 1744128982.149119,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 95,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 46.833843,
      "status": 2,
      "starttime": 1744128982.159532,
      "endtime": 1744128982.1647081,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 96,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 46.84987,
      "status": 2,
      "starttime": 1744128982.175402,
      "endtime": 1744128982.180754,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 97,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 46.866073,
      "status": 2,
      "starttime": 1744128982.192193,
      "endtime": 1744128982.197383,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 98,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 46.881679,
      "status": 2,
      "starttime": 1744128982.20772,
      "endtime": 1744128982.212908,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 99,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 47.921944,
      "status": 2,
      "starttime": 1744128983.292235,
      "endtime": 1744128983.296899,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 100,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 47.937227,
      "status": 2,
      "starttime": 1744128983.307164,
      "endtime": 1744128983.312336,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 101,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 47.954645,
      "status": 2,
      "starttime": 1744128983.32394,
      "endtime": 1744128983.3294458,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 102,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 47.971408,
      "status": 2,
      "starttime": 1744128983.3410728,
      "endtime": 1744128983.346258,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 103,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 47.987626,
      "status": 2,
      "starttime": 1744128983.3571851,
      "endtime": 1744128983.362559,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 104,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 48.00486,
      "status": 2,
      "starttime": 1744128983.374076,
      "endtime": 1744128983.379678,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 105,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 48.02273,
      "status": 2,
      "starttime": 1744128983.392902,
      "endtime": 1744128983.3984709,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 106,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 48.039701,
      "status": 2,
      "starttime": 1744128983.4098501,
      "endtime": 1744128983.4152691,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 107,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 49.060403,
      "status": 2,
      "starttime": 1744128984.433303,
      "endtime": 1744128984.439005,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 108,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 49.077104,
      "status": 2,
      "starttime": 1744128984.450301,
      "endtime": 1744128984.4562829,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 109,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 49.094602,
      "status": 2,
      "starttime": 1744128984.4680161,
      "endtime": 1744128984.473485,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 110,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 49.110886,
      "status": 2,
      "starttime": 1744128984.4841459,
      "endtime": 1744128984.4895308,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 111,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 49.127685,
      "status": 2,
      "starttime": 1744128984.50066,
      "endtime": 1744128984.506067,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 112,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 49.145067,
      "status": 2,
      "starttime": 1744128984.51759,
      "endtime": 1744128984.523107,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 113,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 49.161788,
      "status": 2,
      "starttime": 1744128984.534227,
      "endtime": 1744128984.5399082,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 114,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 49.179189,
      "status": 2,
      "starttime": 1744128984.552922,
      "endtime": 1744128984.558176,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 115,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 50.230878,
      "status": 2,
      "starttime": 1744128985.612469,
      "endtime": 1744128985.61759,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 116,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 50.247702,
      "status": 2,
      "starttime": 1744128985.6290848,
      "endtime": 1744128985.634509,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 117,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 50.265368,
      "status": 2,
      "starttime": 1744128985.64708,
      "endtime": 1744128985.6522398,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 118,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 50.282883,
      "status": 2,
      "starttime": 1744128985.664202,
      "endtime": 1744128985.669405,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 119,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 50.300471,
      "status": 2,
      "starttime": 1744128985.681634,
      "endtime": 1744128985.686781,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 120,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 50.31838,
      "status": 2,
      "starttime": 1744128985.700149,
      "endtime": 1744128985.705475,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 121,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 50.33549,
      "status": 2,
      "starttime": 1744128985.717087,
      "endtime": 1744128985.722486,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 122,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 50.353419,
      "status": 2,
      "starttime": 1744128985.734477,
      "endtime": 1744128985.740055,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 123,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 51.528913,
      "status": 2,
      "starttime": 1744128986.9485,
      "endtime": 1744128986.9539351,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 124,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 51.546995,
      "status": 2,
      "starttime": 1744128986.966327,
      "endtime": 1744128986.971957,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 125,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 51.565242,
      "status": 2,
      "starttime": 1744128986.98419,
      "endtime": 1744128986.9899049,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 126,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 51.583484,
      "status": 2,
      "starttime": 1744128987.002968,
      "endtime": 1744128987.008636,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 127,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 51.60193,
      "status": 2,
      "starttime": 1744128987.021256,
      "endtime": 1744128987.026549,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 128,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 51.619809,
      "status": 2,
      "starttime": 1744128987.038919,
      "endtime": 1744128987.04439,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 129,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 51.638554,
      "status": 2,
      "starttime": 1744128987.057316,
      "endtime": 1744128987.0627031,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 130,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 51.657415,
      "status": 2,
      "starttime": 1744128987.075726,
      "endtime": 1744128987.0809479,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 131,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 52.868162,
      "status": 2,
      "starttime": 1744128988.288001,
      "endtime": 1744128988.293153,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 132,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 52.886508,
      "status": 2,
      "starttime": 1744128988.306014,
      "endtime": 1744128988.31159,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 133,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 52.905381,
      "status": 2,
      "starttime": 1744128988.3256729,
      "endtime": 1744128988.3309572,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 134,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 52.923504,
      "status": 2,
      "starttime": 1744128988.343497,
      "endtime": 1744128988.3489559,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 135,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 52.942193,
      "status": 2,
      "starttime": 1744128988.362852,
      "endtime": 1744128988.368163,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 136,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 52.961024,
      "status": 2,
      "starttime": 1744128988.381509,
      "endtime": 1744128988.386722,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 137,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 52.980026,
      "status": 2,
      "starttime": 1744128988.400647,
      "endtime": 1744128988.405932,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 138,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 52.999263,
      "status": 2,
      "starttime": 1744128988.4195552,
      "endtime": 1744128988.4248772,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 139,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 54.18492,
      "status": 2,
      "starttime": 1744128989.606853,
      "endtime": 1744128989.611934,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 140,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 54.20347,
      "status": 2,
      "starttime": 1744128989.624906,
      "endtime": 1744128989.66659,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 141,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 54.228553,
      "status": 2,
      "starttime": 1744128989.689342,
      "endtime": 1744128989.695819,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 142,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 54.252263,
      "status": 2,
      "starttime": 1744128989.7124422,
      "endtime": 1744128989.7186391,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 143,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 54.275179,
      "status": 2,
      "starttime": 1744128989.735369,
      "endtime": 1744128989.741913,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 144,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 54.298316,
      "status": 2,
      "starttime": 1744128989.7580018,
      "endtime": 1744128989.7642188,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 145,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 54.321736,
      "status": 2,
      "starttime": 1744128989.781146,
      "endtime": 1744128989.787052,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 146,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 54.344122,
      "status": 2,
      "starttime": 1744128989.8032472,
      "endtime": 1744128989.80937,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 147,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 55.617812,
      "status": 2,
      "starttime": 1744128991.084652,
      "endtime": 1744128991.090011,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 148,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 55.63694,
      "status": 2,
      "starttime": 1744128991.103668,
      "endtime": 1744128991.113773,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 149,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 55.658344,
      "status": 2,
      "starttime": 1744128991.129733,
      "endtime": 1744128991.134909,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 150,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 55.677814,
      "status": 2,
      "starttime": 1744128991.148857,
      "endtime": 1744128991.1541262,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 151,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 55.699891,
      "status": 2,
      "starttime": 1744128991.1710699,
      "endtime": 1744128991.176828,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 152,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 55.720957,
      "status": 2,
      "starttime": 1744128991.192271,
      "endtime": 1744128991.197581,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 153,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 55.741729,
      "status": 2,
      "starttime": 1744128991.213734,
      "endtime": 1744128991.2188969,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 154,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 55.761812,
      "status": 2,
      "starttime": 1744128991.2335382,
      "endtime": 1744128991.238878,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 155,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 57.245345,
      "status": 2,
      "starttime": 1744128992.806936,
      "endtime": 1744128992.812146,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 156,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 57.264509,
      "status": 2,
      "starttime": 1744128992.826166,
      "endtime": 1744128992.8314729,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 157,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 57.285775,
      "status": 2,
      "starttime": 1744128992.8476002,
      "endtime": 1744128992.8527832,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 158,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 57.306559,
      "status": 2,
      "starttime": 1744128992.8681111,
      "endtime": 1744128992.873433,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 159,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 57.328875,
      "status": 2,
      "starttime": 1744128992.889907,
      "endtime": 1744128992.895478,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 160,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 57.350227,
      "status": 2,
      "starttime": 1744128992.911139,
      "endtime": 1744128992.916286,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 161,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 57.37024,
      "status": 2,
      "starttime": 1744128992.9314702,
      "endtime": 1744128992.936728,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 162,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 57.390005,
      "status": 2,
      "starttime": 1744128992.95085,
      "endtime": 1744128992.956309,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 163,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 57.455647,
      "status": 2,
      "starttime": 1744128993.016416,
      "endtime": 1744128993.0214632,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 164,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 58.805222,
      "status": 2,
      "starttime": 1744128994.374718,
      "endtime": 1744128994.3798559,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 165,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 58.825531,
      "status": 2,
      "starttime": 1744128994.39469,
      "endtime": 1744128994.3999932,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 166,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 58.84768,
      "status": 2,
      "starttime": 1744128994.416152,
      "endtime": 1744128994.421491,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 167,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 58.869789,
      "status": 2,
      "starttime": 1744128994.437866,
      "endtime": 1744128994.4433439,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 168,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 58.892294,
      "status": 2,
      "starttime": 1744128994.460087,
      "endtime": 1744128994.465497,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 169,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 58.91441,
      "status": 2,
      "starttime": 1744128994.481917,
      "endtime": 1744128994.4874911,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 170,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 58.93663,
      "status": 2,
      "starttime": 1744128994.5039868,
      "endtime": 1744128994.5093892,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 171,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 60.548814,
      "status": 2,
      "starttime": 1744128996.216098,
      "endtime": 1744128996.22138,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 172,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 60.569408,
      "status": 2,
      "starttime": 1744128996.236663,
      "endtime": 1744128996.242372,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 173,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 60.591376,
      "status": 2,
      "starttime": 1744128996.258664,
      "endtime": 1744128996.26412,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 174,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 60.613997,
      "status": 2,
      "starttime": 1744128996.281989,
      "endtime": 1744128996.287642,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 175,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 60.637534,
      "status": 2,
      "starttime": 1744128996.3057878,
      "endtime": 1744128996.311254,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 176,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 60.660525,
      "status": 2,
      "starttime": 1744128996.328785,
      "endtime": 1744128996.334168,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 177,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 60.681997,
      "status": 2,
      "starttime": 1744128996.350167,
      "endtime": 1744128996.355459,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 178,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": Infinity,
      "time": 0.0,
      "cpu_time": 60.703455,
      "status": 2,
      "starttime": 1744128996.371318,
      "endtime": 1744128996.376601,
      "additional_info": {
        "traceback": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 190, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/opt/anaconda3/envs/DASCass2/lib/python3.10/site-packages/smac/runner/target_function_runner.py\", line 264, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/var/folders/9f/8wjgxvzn5gg1rpcnbml_fpw80000gn/T/ipykernel_10405/3173837846.py\", line 5, in target_function\n    model = generate_model()\nNameError: name 'generate_model' is not defined\n",
        "error": "NameError(\"name 'generate_model' is not defined\")"
      }
    },
    {
      "config_id": 179,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": 0.25778451561927795,
      "time": 1071.9026730060577,
      "cpu_time": 10656.866899999999,
      "status": 1,
      "starttime": 1744129123.226588,
      "endtime": 1744130195.129921,
      "additional_info": {}
    },
    {
      "config_id": 180,
      "instance": null,
      "seed": 209652396,
      "budget": null,
      "cost": 2147483647.0,
      "time": 0.0,
      "cpu_time": 0.0,
      "status": 0,
      "starttime": 0.0,
      "endtime": 0.0,
      "additional_info": {}
    }
  ],
  "configs": {
    "1": {
      "factor": 0.2768467429094
    },
    "2": {
      "factor": 0.6586742211133
    },
    "3": {
      "factor": 0.7608361511026
    },
    "4": {
      "factor": 0.1731249728706
    },
    "5": {
      "factor": 0.1339488644619
    },
    "6": {
      "factor": 0.8279367837589
    },
    "7": {
      "factor": 0.5116906934418
    },
    "8": {
      "factor": 0.4486415965483
    },
    "9": {
      "factor": 0.3979263472836
    },
    "10": {
      "factor": 0.5672796641011
    },
    "11": {
      "factor": 0.4564597178618
    },
    "12": {
      "factor": 0.741987318896
    },
    "13": {
      "factor": 0.1693434442824
    },
    "14": {
      "factor": 0.7994419556919
    },
    "15": {
      "factor": 0.7093228591012
    },
    "16": {
      "factor": 0.8365488535385
    },
    "17": {
      "factor": 0.2570277360537
    },
    "18": {
      "factor": 0.7696908542812
    },
    "19": {
      "factor": 0.6508429206499
    },
    "20": {
      "factor": 0.6947570014703
    },
    "21": {
      "factor": 0.6273426208699
    },
    "22": {
      "factor": 0.7606878638182
    },
    "23": {
      "factor": 0.8805907190136
    },
    "24": {
      "factor": 0.3209351721755
    },
    "25": {
      "factor": 0.3833470171482
    },
    "26": {
      "factor": 0.6643158162283
    },
    "27": {
      "factor": 0.7629934062502
    },
    "28": {
      "factor": 0.5084437135983
    },
    "29": {
      "factor": 0.5636725298777
    },
    "30": {
      "factor": 0.4954992597095
    },
    "31": {
      "factor": 0.4385890992811
    },
    "32": {
      "factor": 0.7283020896773
    },
    "33": {
      "factor": 0.2496630486046
    },
    "34": {
      "factor": 0.2986583151922
    },
    "35": {
      "factor": 0.7755750042316
    },
    "36": {
      "factor": 0.6074674491032
    },
    "37": {
      "factor": 0.5261650371614
    },
    "38": {
      "factor": 0.2848233998759
    },
    "39": {
      "factor": 0.7776066472504
    },
    "40": {
      "factor": 0.8072943011461
    },
    "41": {
      "factor": 0.1983903626854
    },
    "42": {
      "factor": 0.3749084018271
    },
    "43": {
      "factor": 0.8862637622537
    },
    "44": {
      "factor": 0.5329575282818
    },
    "45": {
      "factor": 0.437640637355
    },
    "46": {
      "factor": 0.4319387680555
    },
    "47": {
      "factor": 0.686604007267
    },
    "48": {
      "factor": 0.7304409275401
    },
    "49": {
      "factor": 0.5046989707194
    },
    "50": {
      "factor": 0.1636223721661
    },
    "51": {
      "factor": 0.7939790204403
    },
    "52": {
      "factor": 0.5173848899965
    },
    "53": {
      "factor": 0.3190914336347
    },
    "54": {
      "factor": 0.2955977368635
    },
    "55": {
      "factor": 0.3273216926029
    },
    "56": {
      "factor": 0.1961690950689
    },
    "57": {
      "factor": 0.1244359978964
    },
    "58": {
      "factor": 0.8098044276018
    },
    "59": {
      "factor": 0.1724125640664
    },
    "60": {
      "factor": 0.6234906197437
    },
    "61": {
      "factor": 0.1362870544131
    },
    "62": {
      "factor": 0.4218357452287
    },
    "63": {
      "factor": 0.8205262023635
    },
    "64": {
      "factor": 0.1678656016563
    },
    "65": {
      "factor": 0.8479189405622
    },
    "66": {
      "factor": 0.5274769300681
    },
    "67": {
      "factor": 0.4630703268584
    },
    "68": {
      "factor": 0.3781816023143
    },
    "69": {
      "factor": 0.5177762834227
    },
    "70": {
      "factor": 0.5456311799835
    },
    "71": {
      "factor": 0.3767377648376
    },
    "72": {
      "factor": 0.1721878659517
    },
    "73": {
      "factor": 0.4879056333087
    },
    "74": {
      "factor": 0.4013912491712
    },
    "75": {
      "factor": 0.1076182834164
    },
    "76": {
      "factor": 0.421583176076
    },
    "77": {
      "factor": 0.4817134555068
    },
    "78": {
      "factor": 0.5122512740251
    },
    "79": {
      "factor": 0.3306413013996
    },
    "80": {
      "factor": 0.6959908448766
    },
    "81": {
      "factor": 0.096063256537
    },
    "82": {
      "factor": 0.2614266641676
    },
    "83": {
      "factor": 0.7677815178328
    },
    "84": {
      "factor": 0.7359050115422
    },
    "85": {
      "factor": 0.3546434966851
    },
    "86": {
      "factor": 0.4781275185485
    },
    "87": {
      "factor": 0.899732585106
    },
    "88": {
      "factor": 0.8439337960551
    },
    "89": {
      "factor": 0.8016257104751
    },
    "90": {
      "factor": 0.8838943759669
    },
    "91": {
      "factor": 0.3869965834929
    },
    "92": {
      "factor": 0.6692293261948
    },
    "93": {
      "factor": 0.7030228195099
    },
    "94": {
      "factor": 0.4884367465549
    },
    "95": {
      "factor": 0.4490559263306
    },
    "96": {
      "factor": 0.2493531514684
    },
    "97": {
      "factor": 0.368107746979
    },
    "98": {
      "factor": 0.2510056879098
    },
    "99": {
      "factor": 0.7747619684255
    },
    "100": {
      "factor": 0.3657056667959
    },
    "101": {
      "factor": 0.3719910977165
    },
    "102": {
      "factor": 0.1419803782991
    },
    "103": {
      "factor": 0.4445936677108
    },
    "104": {
      "factor": 0.8821088207704
    },
    "105": {
      "factor": 0.4729427001073
    },
    "106": {
      "factor": 0.4398008579225
    },
    "107": {
      "factor": 0.2334843390943
    },
    "108": {
      "factor": 0.1826702403783
    },
    "109": {
      "factor": 0.3566626669854
    },
    "110": {
      "factor": 0.7211646826102
    },
    "111": {
      "factor": 0.5055635122565
    },
    "112": {
      "factor": 0.7868946139047
    },
    "113": {
      "factor": 0.866474440855
    },
    "114": {
      "factor": 0.7158713184191
    },
    "115": {
      "factor": 0.8431859202659
    },
    "116": {
      "factor": 0.0970420167163
    },
    "117": {
      "factor": 0.1128077739463
    },
    "118": {
      "factor": 0.422957529501
    },
    "119": {
      "factor": 0.6693139009316
    },
    "120": {
      "factor": 0.133587642067
    },
    "121": {
      "factor": 0.2830987024101
    },
    "122": {
      "factor": 0.8114413474216
    },
    "123": {
      "factor": 0.2950622788439
    },
    "124": {
      "factor": 0.8469702861311
    },
    "125": {
      "factor": 0.5385958128745
    },
    "126": {
      "factor": 0.3959646528445
    },
    "127": {
      "factor": 0.5316818901294
    },
    "128": {
      "factor": 0.1673675037128
    },
    "129": {
      "factor": 0.3700077833538
    },
    "130": {
      "factor": 0.4787302992962
    },
    "131": {
      "factor": 0.1363865411874
    },
    "132": {
      "factor": 0.49055534673
    },
    "133": {
      "factor": 0.5557556670619
    },
    "134": {
      "factor": 0.7527321215318
    },
    "135": {
      "factor": 0.321016181986
    },
    "136": {
      "factor": 0.8019882574294
    },
    "137": {
      "factor": 0.2112618340543
    },
    "138": {
      "factor": 0.2476266687572
    },
    "139": {
      "factor": 0.4684246080611
    },
    "140": {
      "factor": 0.3892503413382
    },
    "141": {
      "factor": 0.8530049613983
    },
    "142": {
      "factor": 0.3279659606915
    },
    "143": {
      "factor": 0.2569188421136
    },
    "144": {
      "factor": 0.558528049793
    },
    "145": {
      "factor": 0.1494611171022
    },
    "146": {
      "factor": 0.6091057883226
    },
    "147": {
      "factor": 0.4716063725859
    },
    "148": {
      "factor": 0.1083167182644
    },
    "149": {
      "factor": 0.4069728607872
    },
    "150": {
      "factor": 0.3145273741818
    },
    "151": {
      "factor": 0.3028669211785
    },
    "152": {
      "factor": 0.7515961322057
    },
    "153": {
      "factor": 0.0836112952162
    },
    "154": {
      "factor": 0.1381345547727
    },
    "155": {
      "factor": 0.6107268361889
    },
    "156": {
      "factor": 0.8889150557101
    },
    "157": {
      "factor": 0.4730173279275
    },
    "158": {
      "factor": 0.8097463661621
    },
    "159": {
      "factor": 0.7620223184589
    },
    "160": {
      "factor": 0.4751932612233
    },
    "161": {
      "factor": 0.2559487830419
    },
    "162": {
      "factor": 0.6595376765719
    },
    "163": {
      "factor": 0.1766009928559
    },
    "164": {
      "factor": 0.2499995133186
    },
    "165": {
      "factor": 0.8482714239049
    },
    "166": {
      "factor": 0.5597023840301
    },
    "167": {
      "factor": 0.3665218204388
    },
    "168": {
      "factor": 0.3364864344712
    },
    "169": {
      "factor": 0.6896960500971
    },
    "170": {
      "factor": 0.779110498756
    },
    "171": {
      "factor": 0.5455656760985
    },
    "172": {
      "factor": 0.0861451765225
    },
    "173": {
      "factor": 0.2191123705442
    },
    "174": {
      "factor": 0.4468462848416
    },
    "175": {
      "factor": 0.7512008174382
    },
    "176": {
      "factor": 0.5915692020609
    },
    "177": {
      "factor": 0.4111769581703
    },
    "178": {
      "factor": 0.177637593062
    },
    "179": {
      "factor": 0.504857894004
    },
    "180": {
      "factor": 0.6719037692618
    }
  },
  "config_origins": {
    "1": "Initial Design: Sobol",
    "2": "Initial Design: Sobol",
    "3": "Initial Design: Sobol",
    "4": "Initial Design: Sobol",
    "5": "Initial Design: Sobol",
    "6": "Initial Design: Sobol",
    "7": "Initial Design: Sobol",
    "8": "Initial Design: Sobol",
    "9": "Initial Design: Sobol",
    "10": "Initial Design: Sobol",
    "11": "Acquisition Function Maximizer: Local Search",
    "12": "Acquisition Function Maximizer: Local Search",
    "13": "Acquisition Function Maximizer: Local Search",
    "14": "Acquisition Function Maximizer: Local Search",
    "15": "Acquisition Function Maximizer: Local Search",
    "16": "Acquisition Function Maximizer: Local Search",
    "17": "Acquisition Function Maximizer: Local Search",
    "18": "Acquisition Function Maximizer: Local Search",
    "19": "Acquisition Function Maximizer: Local Search",
    "20": "Acquisition Function Maximizer: Local Search",
    "21": "Acquisition Function Maximizer: Local Search",
    "22": "Acquisition Function Maximizer: Local Search",
    "23": "Acquisition Function Maximizer: Local Search",
    "24": "Acquisition Function Maximizer: Local Search",
    "25": "Random Search",
    "26": "Random Search",
    "27": "Random Search",
    "28": "Acquisition Function Maximizer: Local Search",
    "29": "Acquisition Function Maximizer: Local Search",
    "30": "Acquisition Function Maximizer: Local Search",
    "31": "Acquisition Function Maximizer: Local Search",
    "32": "Acquisition Function Maximizer: Local Search",
    "33": "Acquisition Function Maximizer: Local Search",
    "34": "Acquisition Function Maximizer: Local Search",
    "35": "Random Search",
    "36": "Acquisition Function Maximizer: Local Search",
    "37": "Random Search",
    "38": "Acquisition Function Maximizer: Local Search",
    "39": "Acquisition Function Maximizer: Local Search",
    "40": "Acquisition Function Maximizer: Local Search",
    "41": "Acquisition Function Maximizer: Local Search",
    "42": "Acquisition Function Maximizer: Local Search",
    "43": "Acquisition Function Maximizer: Local Search",
    "44": "Acquisition Function Maximizer: Local Search",
    "45": "Random Search",
    "46": "Acquisition Function Maximizer: Local Search",
    "47": "Acquisition Function Maximizer: Local Search",
    "48": "Acquisition Function Maximizer: Local Search",
    "49": "Acquisition Function Maximizer: Local Search",
    "50": "Acquisition Function Maximizer: Local Search",
    "51": "Acquisition Function Maximizer: Local Search",
    "52": "Acquisition Function Maximizer: Local Search",
    "53": "Acquisition Function Maximizer: Local Search",
    "54": "Random Search",
    "55": "Acquisition Function Maximizer: Local Search",
    "56": "Acquisition Function Maximizer: Local Search",
    "57": "Acquisition Function Maximizer: Local Search",
    "58": "Random Search",
    "59": "Acquisition Function Maximizer: Local Search",
    "60": "Acquisition Function Maximizer: Local Search",
    "61": "Acquisition Function Maximizer: Local Search",
    "62": "Acquisition Function Maximizer: Local Search",
    "63": "Acquisition Function Maximizer: Local Search",
    "64": "Random Search",
    "65": "Acquisition Function Maximizer: Local Search",
    "66": "Random Search",
    "67": "Acquisition Function Maximizer: Local Search",
    "68": "Acquisition Function Maximizer: Local Search",
    "69": "Acquisition Function Maximizer: Local Search",
    "70": "Acquisition Function Maximizer: Local Search",
    "71": "Random Search",
    "72": "Random Search",
    "73": "Acquisition Function Maximizer: Local Search",
    "74": "Random Search",
    "75": "Random Search",
    "76": "Acquisition Function Maximizer: Local Search",
    "77": "Acquisition Function Maximizer: Local Search",
    "78": "Random Search",
    "79": "Acquisition Function Maximizer: Local Search",
    "80": "Random Search",
    "81": "Acquisition Function Maximizer: Local Search",
    "82": "Acquisition Function Maximizer: Local Search",
    "83": "Acquisition Function Maximizer: Local Search",
    "84": "Acquisition Function Maximizer: Local Search",
    "85": "Acquisition Function Maximizer: Local Search",
    "86": "Random Search",
    "87": "Acquisition Function Maximizer: Local Search",
    "88": "Random Search",
    "89": "Acquisition Function Maximizer: Local Search",
    "90": "Random Search",
    "91": "Acquisition Function Maximizer: Local Search",
    "92": "Acquisition Function Maximizer: Local Search",
    "93": "Random Search",
    "94": "Acquisition Function Maximizer: Local Search",
    "95": "Acquisition Function Maximizer: Local Search",
    "96": "Acquisition Function Maximizer: Local Search",
    "97": "Acquisition Function Maximizer: Local Search",
    "98": "Random Search",
    "99": "Acquisition Function Maximizer: Local Search",
    "100": "Acquisition Function Maximizer: Local Search",
    "101": "Acquisition Function Maximizer: Local Search",
    "102": "Acquisition Function Maximizer: Local Search",
    "103": "Random Search",
    "104": "Acquisition Function Maximizer: Local Search",
    "105": "Acquisition Function Maximizer: Local Search",
    "106": "Random Search",
    "107": "Acquisition Function Maximizer: Local Search",
    "108": "Random Search",
    "109": "Acquisition Function Maximizer: Local Search",
    "110": "Random Search",
    "111": "Acquisition Function Maximizer: Local Search",
    "112": "Acquisition Function Maximizer: Local Search",
    "113": "Acquisition Function Maximizer: Local Search",
    "114": "Acquisition Function Maximizer: Local Search",
    "115": "Acquisition Function Maximizer: Local Search",
    "116": "Acquisition Function Maximizer: Local Search",
    "117": "Acquisition Function Maximizer: Local Search",
    "118": "Acquisition Function Maximizer: Local Search",
    "119": "Acquisition Function Maximizer: Local Search",
    "120": "Acquisition Function Maximizer: Local Search",
    "121": "Acquisition Function Maximizer: Local Search",
    "122": "Acquisition Function Maximizer: Local Search",
    "123": "Acquisition Function Maximizer: Local Search",
    "124": "Acquisition Function Maximizer: Local Search",
    "125": "Acquisition Function Maximizer: Local Search",
    "126": "Acquisition Function Maximizer: Local Search",
    "127": "Acquisition Function Maximizer: Local Search",
    "128": "Acquisition Function Maximizer: Local Search",
    "129": "Acquisition Function Maximizer: Local Search",
    "130": "Acquisition Function Maximizer: Local Search",
    "131": "Acquisition Function Maximizer: Local Search",
    "132": "Acquisition Function Maximizer: Local Search",
    "133": "Acquisition Function Maximizer: Local Search",
    "134": "Acquisition Function Maximizer: Local Search",
    "135": "Acquisition Function Maximizer: Local Search",
    "136": "Acquisition Function Maximizer: Local Search",
    "137": "Random Search",
    "138": "Acquisition Function Maximizer: Local Search",
    "139": "Acquisition Function Maximizer: Local Search",
    "140": "Acquisition Function Maximizer: Local Search",
    "141": "Acquisition Function Maximizer: Local Search",
    "142": "Acquisition Function Maximizer: Local Search",
    "143": "Random Search",
    "144": "Acquisition Function Maximizer: Local Search",
    "145": "Acquisition Function Maximizer: Local Search",
    "146": "Acquisition Function Maximizer: Local Search",
    "147": "Acquisition Function Maximizer: Local Search",
    "148": "Acquisition Function Maximizer: Local Search",
    "149": "Acquisition Function Maximizer: Local Search",
    "150": "Acquisition Function Maximizer: Local Search",
    "151": "Acquisition Function Maximizer: Local Search",
    "152": "Acquisition Function Maximizer: Local Search",
    "153": "Acquisition Function Maximizer: Local Search",
    "154": "Acquisition Function Maximizer: Local Search",
    "155": "Acquisition Function Maximizer: Local Search",
    "156": "Acquisition Function Maximizer: Local Search",
    "157": "Random Search",
    "158": "Acquisition Function Maximizer: Local Search",
    "159": "Acquisition Function Maximizer: Local Search",
    "160": "Acquisition Function Maximizer: Local Search",
    "161": "Random Search",
    "162": "Acquisition Function Maximizer: Local Search",
    "163": "Random Search",
    "164": "Acquisition Function Maximizer: Local Search",
    "165": "Random Search",
    "166": "Acquisition Function Maximizer: Local Search",
    "167": "Acquisition Function Maximizer: Local Search",
    "168": "Acquisition Function Maximizer: Local Search",
    "169": "Acquisition Function Maximizer: Local Search",
    "170": "Random Search",
    "171": "Acquisition Function Maximizer: Local Search",
    "172": "Acquisition Function Maximizer: Local Search",
    "173": "Acquisition Function Maximizer: Local Search",
    "174": "Acquisition Function Maximizer: Local Search",
    "175": "Acquisition Function Maximizer: Local Search",
    "176": "Acquisition Function Maximizer: Local Search",
    "177": "Random Search",
    "178": "Acquisition Function Maximizer: Local Search",
    "179": "Acquisition Function Maximizer: Local Search",
    "180": "Acquisition Function Maximizer: Local Search"
  }
}